name: Combine AZ & TR IPTV Lists

on:
  schedule:
    - cron: '0 */6 * * *' # Hər 6 saatdan bir çalışır
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run combine script
        run: |
          python combine_m3u.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add az_tr.m3u
          git commit -m "AZ və TR M3U siyahıları birləşdirildi və yeniləndi" || echo "No changes to commit"
          git push
